### ISSUE TITLE
Afk Auto Kick

### ISSUE THREAD

**Issue by nhoclesnar** [CommandsEX/Minecraft-CommandsEX#13]
Auto kicking afk players in the server to make empty slots for others to join.

When a player stops moving or interacting with objects, that player will be kicked after a certain amount of time. The player will be kicked using the command '/kick [reason]', where the [reason] is the message sent to the kicked player.

In the config file, two new options added: a custom kick time, and a custom kick message sent to the kicked player.

**Comment by nhoclesnar** [comment]
Oh, and can you please add permission to exclude certain people from being monitored for afk and afk kicking? I forgot that I do not want Admins to be kicked :)

**Comment by keir-nellyer** [comment]
Ok, will do!

**Comment by keir-nellyer** [comment]
Added!

**Comment by sossos1988** [comment]
What is the Permission node for this?
