### ISSUE TITLE
PlayerJoinEvent error on CB1.4.2-R0.1[Beta #2446]

### ISSUE THREAD

**Issue by Fronix** [CommandsEX/Minecraft-CommandsEX#16]
Getting this error when I join my server http://pastebin.com/vSD49adm

Nothing brakes It just pops up on join and everything works after that.

**Comment by keir-nellyer** [comment]
Thanks for reporting we fixed the issue and it will be available in CommandsEX 2.0 which we hope to release soon!

Thanks
Keir
