### ISSUE TITLE
EntityDamage?

### ISSUE THREAD

**Issue by Xarias09** [CommandsEX/Minecraft-CommandsEX#17]
Bukkit: #2457 build
CommandsEX: 1.98

Error:
http://pastebin.com/9QjSGvfP

**Comment by keir-nellyer** [comment]
I'm not sure why you are getting that error, does it happen often? It might just be a strange thing that occasionally happens.

**Comment by Xarias09** [comment]
Spam a lot.. ;3 maybe because i have plugin which allow some players to fly in survival mode?

But this plugin have blocked PVP :# dont have any other ideas

**Comment by keir-nellyer** [comment]
I don't think that's why, I'll keep looking into it. Can you send a full list of your plugins?

**Comment by keir-nellyer** [comment]
I believe I have fixed the issue, I realized that I was looking at a newer version of the code than you and that's why I couldn't figure out why it was happening.
