### ISSUE TITLE
/nick -

### ISSUE THREAD

**Issue by ghost** [CommandsEX/Minecraft-CommandsEX#18]
Hello

Would it be possible to make it so people can't change there nicknames into a name that is used either as there minecraft name or display name?

At the moment in the current version of Bukkit, 1.4.2 R2 Beta one, it gives an Internal Error but still allows the player to have the name as somebody.

Kindest Regards,

**Comment by keir-nellyer** [comment]
So you want to stop people from changing the nickname to a player that is on the server? If so I will also add a bypass node to bypass that restriction

**Comment by ghost** [comment]
Correct. Basically, at the moment when someone is to change there nickname to an existing name they firstly get an internal error but there nickname still changes. 

We need a restriction that solves that.

I have a few bug reports that are in the latest bukkit, for example /jail & /whois. If you need the error, let me know.

**Comment by keir-nellyer** [comment]
Okay, will look into it. As for the other errors I would like to know, please post them as separate issues.

**Comment by keir-nellyer** [comment]
Fixed this issue, although if 2 or more players already had their nickname set the same, they will have to have their nicknames reset for the fix to take place.
