### ISSUE TITLE
Server rebooting every minute or so.

### ISSUE THREAD

**Issue by sossos1988** [CommandsEX/Minecraft-CommandsEX#21]
When I have all my plugins enabled plus CommandsEX the server boots up fine then after a minute or so it reboots. If I disable CommandsEX only and boot the server I dont have any issues with the server rebooting. I have tried both the 1.98 and 1.97 versions and get the same outcome. I am also on the latest Recommended build of Bukkit and have Java 7. Here is a link to my server log http://pastie.org/5412840 I dont see anything out of the ordinary to suggest anything is wrong but it is rebooting constantly.

Thanks in advance

Aaron

**Comment by sossos1988** [comment]
Aslo a note is I use Multicraft for my servers.

**Comment by keir-nellyer** [comment]
From what you said it sounds like this isn't a CommandsEX problem and that another plugin is causing this. I would suggest removing each plugin one by one and then checking if the problem persists. Then you will be able to trace the problem.
