### ISSUE TITLE
CommandsEX v2.00 DEV, Spigot: #344 - PlayerJoinEvent

### ISSUE THREAD

**Issue by Xarias09** [CommandsEX/Minecraft-CommandsEX#26]
Hi!,

It appears when player log in to my beta server:

http://pastebin.com/8KJJRZ1g

Here is plugin + config which i generated at this URL: http://commandsex.sourceforge.net/dev/

http://dl.dropbox.com/u/47735165/Desktop.rar

Greetings

**Comment by Xarias09** [comment]
PasteBin:

Appearing when i log out:
http://pastebin.com/Rreb1YiA

---

Spam:
http://pastebin.com/9JNVSqMG

**Comment by Xarias09** [comment]
/reply command don't work - plugin appearing a message "You no one to whom you can reply to" :3333

**Comment by keir-nellyer** [comment]
This is due to a CraftBukkit change meaning that some stuff will break with every update. CommandsEX does not yet support 1.4.6 but we will start releasing dev builds for it once we release a version for 1.4.5 which will be soon.

Either disable CommandsEX or downgrade to 1.4.5 til there is a version available.

**Comment by Xarias09** [comment]
I use second method ;D at 1.4.5 works fine but the reply command don't work still ;D

**Comment by keir-nellyer** [comment]
/reply only works if you have the /msg command enabled and also if someone messaged you. Also we have dev builds for 1.4.6 now. http://commandsex.sourceforge.net/21DEV146/

**Comment by Xarias09** [comment]
but i have message enabled, i send to my friend message using this command: /message Admin TEST and after it i try to type /reply blablabla :C

**Comment by keir-nellyer** [comment]
/reply only works if someone sends YOU a message. In the above example your friend would be able to do /reply
