### ISSUE TITLE
CommandsEx startup error

### ISSUE THREAD

**Issue by foxhoundvenom** [CommandsEX/Minecraft-CommandsEX#28]
I am running CraftBukkit #2552 and This is the error I get:

09:33 AM [INFO] [CommandsEX] Enabling CommandsEX v2.0 
09:33 AM [INFO] [CommandsEX] Starting with locale (translation): en 
09:33 AM [INFO] [CommandsEX] version 2.0 has successfully started. 
09:33 AM [SEVERE] An internal error has occured. Please try again, download a newer version of CommandsEX or contact the author. 
09:33 AM [SEVERE] java.lang.reflect.InvocationTargetException 
09:33 AM [SEVERE] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 
09:33 AM [SEVERE] at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) 
09:33 AM [SEVERE] at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) 
09:33 AM [SEVERE] at java.lang.reflect.Method.invoke(Unknown Source) 
09:33 AM [SEVERE] at com.github.zathrus_writer.commandsex.CommandsEX.onEnable(CommandsEX.java:179) 
09:33 AM [SEVERE] at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:217) 
09:33 AM [SEVERE] at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:457) 
09:33 AM [SEVERE] at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:381) 
09:33 AM [SEVERE] at org.bukkit.craftbukkit.v1_4_6.CraftServer.loadPlugin(CraftServer.java:278) 
09:33 AM [SEVERE] at org.bukkit.craftbukkit.v1_4_6.CraftServer.enablePlugins(CraftServer.java:260) 
09:33 AM [SEVERE] at net.minecraft.server.v1_4_6.MinecraftServer.j(MinecraftServer.java:321) 
09:33 AM [SEVERE] at net.minecraft.server.v1_4_6.MinecraftServer.e(MinecraftServer.java:300) 
09:33 AM [SEVERE] at net.minecraft.server.v1_4_6.MinecraftServer.a(MinecraftServer.java:259) 
09:33 AM [SEVERE] at net.minecraft.server.v1_4_6.DedicatedServer.init(DedicatedServer.java:149) 
09:33 AM [SEVERE] at net.minecraft.server.v1_4_6.MinecraftServer.run(MinecraftServer.java:399) 
09:33 AM [SEVERE] at net.minecraft.server.v1_4_6.ThreadServerApplication.run(SourceFile:849) 
09:33 AM [SEVERE] Caused by: java.lang.NoClassDefFoundError: net/minecraft/server/v1_4_5/World 
09:33 AM [SEVERE] at com.github.zathrus_writer.commandsex.helpers.Quizzes.init(Quizzes.java:63) 
09:33 AM [SEVERE] ... 16 more 
09:33 AM [SEVERE] Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_4_5.World 
09:33 AM [SEVERE] at org.bukkit.plugin.java.PluginClassLoader.findClass0(PluginClassLoader.java:70) 
09:33 AM [SEVERE] at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:53) 
09:33 AM [SEVERE] at java.lang.ClassLoader.loadClass(Unknown Source) 
09:33 AM [SEVERE] ... 17 more 
09:33 AM [SEVERE] An internal error has occured. Please try again, download a newer version of CommandsEX or contact the author. 
09:33 AM [SEVERE] java.lang.NoClassDefFoundError: net/minecraft/server/v1_4_5/World 
09:33 AM [SEVERE] at com.github.zathrus_writer.commandsex.handlers.Handler_condensejoins.<clinit>(Handler_condensejoins.java:35) 
09:33 AM [SEVERE] at java.lang.Class.forName0(Native Method) 
09:33 AM [SEVERE] at java.lang.Class.forName(Unknown Source) 
09:33 AM [SEVERE] at com.github.zathrus_writer.commandsex.CommandsEX.onEnable(CommandsEX.java:163) 
09:33 AM [SEVERE] at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:217) 
09:33 AM [SEVERE] at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:457) 
09:33 AM [SEVERE] at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:381) 
09:33 AM [SEVERE] at org.bukkit.craftbukkit.v1_4_6.CraftServer.loadPlugin(CraftServer.java:278) 
09:33 AM [SEVERE] at org.bukkit.craftbukkit.v1_4_6.CraftServer.enablePlugins(CraftServer.java:260) 
09:33 AM [SEVERE] at net.minecraft.server.v1_4_6.MinecraftServer.j(MinecraftServer.java:321) 
09:33 AM [SEVERE] at net.minecraft.server.v1_4_6.MinecraftServer.e(MinecraftServer.java:300) 
09:33 AM [SEVERE] at net.minecraft.server.v1_4_6.MinecraftServer.a(MinecraftServer.java:259) 
09:33 AM [SEVERE] at net.minecraft.server.v1_4_6.DedicatedServer.init(DedicatedServer.java:149) 
09:33 AM [SEVERE] at net.minecraft.server.v1_4_6.MinecraftServer.run(MinecraftServer.java:399) 
09:33 AM [SEVERE] at net.minecraft.server.v1_4_6.ThreadServerApplication.run(SourceFile:849) 
09:33 AM [SEVERE] Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_4_5.World 
09:33 AM [SEVERE] at org.bukkit.plugin.java.PluginClassLoader.findClass0(PluginClassLoader.java:70) 
09:33 AM [SEVERE] at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:53) 
09:33 AM [SEVERE] at java.lang.ClassLoader.loadClass(Unknown Source) 
09:33 AM [SEVERE] ... 15 more 
09:33 AM [SEVERE] An internal error has occured. Please try again, download a newer version of CommandsEX or contact the author. 
09:33 AM [SEVERE] java.lang.NoClassDefFoundError: net/minecraft/server/v1_4_5/World 
09:33 AM [SEVERE] at com.github.zathrus_writer.commandsex.helpers.XMPPer.<clinit>(XMPPer.java:43) 
09:33 AM [SEVERE] at com.github.zathrus_writer.commandsex.handlers.Handler_xmpp.<init>(Handler_xmpp.java:30) 
09:33 AM [SEVERE] at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) 
09:33 AM [SEVERE] at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) 
09:33 AM [SEVERE] at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) 
09:33 AM [SEVERE] at java.lang.reflect.Constructor.newInstance(Unknown Source) 
09:33 AM [SEVERE] at java.lang.Class.newInstance0(Unknown Source) 
09:33 AM [SEVERE] at java.lang.Class.newInstance(Unknown Source) 
09:33 AM [SEVERE] at com.github.zathrus_writer.commandsex.CommandsEX.onEnable(CommandsEX.java:163) 
09:33 AM [SEVERE] at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:217) 
09:33 AM [SEVERE] at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:457) 
09:33 AM [SEVERE] at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:381) 
09:33 AM [SEVERE] at org.bukkit.craftbukkit.v1_4_6.CraftServer.loadPlugin(CraftServer.java:278) 
09:33 AM [SEVERE] at org.bukkit.craftbukkit.v1_4_6.CraftServer.enablePlugins(CraftServer.java:260) 
09:33 AM [SEVERE] at net.minecraft.server.v1_4_6.MinecraftServer.j(MinecraftServer.java:321) 
09:33 AM [SEVERE] at net.minecraft.server.v1_4_6.MinecraftServer.e(MinecraftServer.java:300) 
09:33 AM [SEVERE] at net.minecraft.server.v1_4_6.MinecraftServer.a(MinecraftServer.java:259) 
09:33 AM [SEVERE] at net.minecraft.server.v1_4_6.DedicatedServer.init(DedicatedServer.java:149) 
09:33 AM [SEVERE] at net.minecraft.server.v1_4_6.MinecraftServer.run(MinecraftServer.java:399) 
09:33 AM [SEVERE] at net.minecraft.server.v1_4_6.ThreadServerApplication.run(SourceFile:849) 
09:33 AM [SEVERE] Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_4_5.World 
09:33 AM [SEVERE] at org.bukkit.plugin.java.PluginClassLoader.findClass0(PluginClassLoader.java:70) 
09:33 AM [SEVERE] at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:53) 
09:33 AM [SEVERE] at java.lang.ClassLoader.loadClass(Unknown Source) 
09:33 AM [SEVERE] ... 20 more 

Other plugins installed:
AntiCheat
Builder(for Denizen part of Citizens2)
ChatManager
Citizens
CommandBook
CommandsEX
CraftBukkitUpToDate
Denizen
Hawkeye
IPSecurity
LoginSecurity
Modifyworld
Multiverse-Core
OnTime
Pail
PermissionsEx
PluginMetrics
Ptweaks
RangeBans
Stargate
Towny
Vault
va_Postal(part of Citizens)
Wither
WorldEdit
WorldGuard

All the other Plugins work fine.  This is my first time submiting any problems please let me know if you need anything else!

**Comment by foxhoundvenom** [comment]
Shortly followed by:

10:27 AM [WARNING] [CommandsEX] Task #13 for CommandsEX v2.0 generated an exception 
10:27 AM [SEVERE] Exception in thread "pool-1-thread-21" 
10:27 AM [SEVERE] Exception in thread "pool-11-thread-1" 
10:27 AM [SEVERE] org.apache.commons.lang.UnhandledException: Plugin CommandsEX v2.0 generated an exception while executing task 14
    at org.bukkit.craftbukkit.v1_4_6.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NoClassDefFoundError: net/minecraft/server/v1_4_5/World
    at com.github.zathrus_writer.commandsex.CommandsEX$1.run(CommandsEX.java:198)
    at org.bukkit.craftbukkit.v1_4_6.scheduler.CraftTask.run(CraftTask.java:53)
    at org.bukkit.craftbukkit.v1_4_6.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
    ... 3 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_4_5.World
    at org.bukkit.plugin.java.PluginClassLoader.findClass0(PluginClassLoader.java:70)
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:53)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 6 more 
10:27 AM [SEVERE] java.lang.NullPointerException 
10:27 AM [SEVERE] at net.milkbowl.vault.permission.Permission.getPlayerGroups(Permission.java:610) 
10:27 AM [SEVERE] at com.github.zathrus_writer.commandsex.helpers.Promotions.checkTimedPromotions(Promotions.java:70) 
10:27 AM [SEVERE] at com.github.zathrus_writer.commandsex.handlers.Handler_playtimepromote$1$1.run(Handler_playtimepromote.java:52) 
10:27 AM [SEVERE] at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) 
10:27 AM [SEVERE] at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) 
10:27 AM [SEVERE] at java.lang.Thread.run(Unknown Source) 
10:30 AM [SEVERE] Exception in thread "pool-1-thread-24" 
10:30 AM [SEVERE] org.apache.commons.lang.UnhandledException: Plugin CommandsEX v2.0 generated an exception while executing task 14
    at org.bukkit.craftbukkit.v1_4_6.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NoClassDefFoundError: net/minecraft/server/v1_4_5/World
    at com.github.zathrus_writer.commandsex.CommandsEX$1.run(CommandsEX.java:198)
    at org.bukkit.craftbukkit.v1_4_6.scheduler.CraftTask.run(CraftTask.java:53)
    at org.bukkit.craftbukkit.v1_4_6.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
    ... 3 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_4_5.World
    at org.bukkit.plugin.java.PluginClassLoader.findClass0(PluginClassLoader.java:70)
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:53)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 6 more 
10:30 AM [SEVERE] Exception in thread "pool-12-thread-1" 
10:30 AM [SEVERE] java.lang.NullPointerException 
10:30 AM [SEVERE] at net.milkbowl.vault.permission.Permission.getPlayerGroups(Permission.java:610) 
10:30 AM [SEVERE] at com.github.zathrus_writer.commandsex.helpers.Promotions.checkTimedPromotions(Promotions.java:70) 
10:30 AM [SEVERE] at com.github.zathrus_writer.commandsex.handlers.Handler_playtimepromote$1$1.run(Handler_playtimepromote.java:52) 
10:30 AM [SEVERE] at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) 
10:30 AM [SEVERE] at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) 
10:30 AM [SEVERE] at java.lang.Thread.run(Unknown Source) 
10:33 AM [SEVERE] Exception in thread "pool-1-thread-32" 
10:33 AM [SEVERE] org.apache.commons.lang.UnhandledException: Plugin CommandsEX v2.0 generated an exception while executing task 14
    at org.bukkit.craftbukkit.v1_4_6.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NoClassDefFoundError: net/minecraft/server/v1_4_5/World
    at com.github.zathrus_writer.commandsex.CommandsEX$1.run(CommandsEX.java:198)
    at org.bukkit.craftbukkit.v1_4_6.scheduler.CraftTask.run(CraftTask.java:53)
    at org.bukkit.craftbukkit.v1_4_6.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
    ... 3 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_4_5.World
    at org.bukkit.plugin.java.PluginClassLoader.findClass0(PluginClassLoader.java:70)
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:53)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 6 more 
10:33 AM [SEVERE] Exception in thread "pool-13-thread-1" 
10:33 AM [SEVERE] java.lang.NullPointerException 
10:33 AM [SEVERE] at net.milkbowl.vault.permission.Permission.getPlayerGroups(Permission.java:610) 
10:33 AM [SEVERE] at com.github.zathrus_writer.commandsex.helpers.Promotions.checkTimedPromotions(Promotions.java:70) 
10:33 AM [SEVERE] at com.github.zathrus_writer.commandsex.handlers.Handler_playtimepromote$1$1.run(Handler_playtimepromote.java:52) 
10:33 AM [SEVERE] at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) 
10:33 AM [SEVERE] at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) 
10:33 AM [SEVERE] at java.lang.Thread.run(Unknown Source)

**Comment by keir-nellyer** [comment]
The first error is caused by a recent CraftBukkit commit which causes CommandsEX to break with every update. You need to rebuild CommandsEX using the 1.4.6 version found here http://commandsex.sourceforge.net/21DEV146/

Or if you did not use the Builder then you can get a developement build here http://build.yu8.me:8090/job/CommandsEX/lastBuild/artifact/CommandsEX-42.jar

The second error seems to be caused by Vault, CommandsEX is running code thats inside Vault and Vault is creating an error. Make sure your using the latest version of Vault and if that doesn't fix it then you might want to report it to Vault. I personally haven't experienced this error yet but it might be because you have a different setup.

**Comment by foxhoundvenom** [comment]
Thank You so much

**Comment by keir-nellyer** [comment]
No problem, I guess it worked?

**Comment by foxhoundvenom** [comment]
yes it did
