### ISSUE TITLE
Broadcast bug

### ISSUE THREAD

**Issue by Xarias09** [CommandsEX/Minecraft-CommandsEX#29]
Latest spigot, CommandsEX: v2.1 DEV
Don't know what cause this (nullpointer - no sender maybe?)

http://pastebin.com/KSFNAwsg

**Comment by keir-nellyer** [comment]
There is no mention of CommandsEX in there, your server seems to be using the Built in Say Command instead of the one from CommandsEX. This looks like an issue with PermissionsEX, do you have the latest version of PermissionsEX?

This does not appear to be an issue with CommandsEX

**Comment by JamesNorris** [comment]
If you are using PermissionsEX, I highly reccommend switching to bPermissions. With the new changed to NMS and OBC, PEX is going to screw everything up that it can. It works against Bukkit, not with it. Luckily bPerms has a PEX converter for your permissions!

"Whatever can go wrong, will go wrong."
