### ISSUE TITLE
MobArena + CommandsEX

### ISSUE THREAD

**Issue by Xarias09** [CommandsEX/Minecraft-CommandsEX#37]
Spigot: 396
CommandsEX: 1.4.6 (v2.1 dev)
MobArena: v0.94.4.91

PasteBin:
http://pastebin.com/Wzs9p1NT

It appear sometimes, don't know why...
"at com.github.zathrus_writer.commandsex.helpers.Common$Unslap.run(Common.java:92)"

**Comment by keir-nellyer** [comment]
Fixed, I currently can't send the code to GitHub because my Jenkins server isn't up yet. I'll push it to GitHub when it is though
