### ISSUE TITLE
XMPP (Jabber) Chat Relay doesnt send Chat to Server

### ISSUE THREAD

**Issue by fr34kyn01535** [CommandsEX/Minecraft-CommandsEX#4]
I am able to send Chat and Commands to my Server ("11:07:27 [INFO] +djrazr_: Hello Minecraft!") but if i write somethin into Chat i get: 

11:08:36 [SEVERE] java.lang.InterruptedException
11:08:36 [SEVERE]       at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireInterruptibly(Unknown Source)
11:08:36 [SEVERE]       at java.util.concurrent.locks.ReentrantLock.lockInterruptibly(Unknown Source)
11:08:36 [SEVERE]       at java.util.concurrent.ArrayBlockingQueue.put(Unknown Source)
11:08:36 [SEVERE]       at org.jivesoftware.smack.PacketWriter.sendPacket(PacketWriter.java:95)
11:08:36 [SEVERE]       at org.jivesoftware.smack.XMPPConnection.sendPacket(XMPPConnection.java:450)
11:08:36 [SEVERE]       at org.jivesoftware.smackx.muc.MultiUserChat.sendMessage(MultiUserChat.java:1824)
11:08:36 [SEVERE]       at com.github.zathrus_writer.commandsex.helpers.XMPPer.interceptChat(XMPPer.java:142)
11:08:36 [SEVERE]       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
11:08:36 [SEVERE]       at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
11:08:36 [SEVERE]       at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
11:08:36 [SEVERE]       at java.lang.reflect.Method.invoke(Unknown Source)
11:08:36 [SEVERE]       at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:330)
11:08:36 [SEVERE]       at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
11:08:36 [SEVERE]       at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:477)
11:08:36 [SEVERE]       at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:459)
11:08:36 [SEVERE]       at net.minecraft.server.NetServerHandler.chat(NetServerHandler.java:830)
11:08:36 [SEVERE]       at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:807)
11:08:36 [SEVERE]       at net.minecraft.server.Packet3Chat.handle(Packet3Chat.java:44)
11:08:36 [SEVERE]       at net.minecraft.server.NetworkManager.i(NetworkManager.java:211)
11:08:36 [SEVERE]       at net.minecraft.server.NetworkManager.c(NetworkManager.java:326)
11:08:36 [SEVERE]       at net.minecraft.server.NetworkReaderThread.run(SourceFile:93)
11:08:36 [INFO] 11:08:36 |||||||||| [Player] djrazr: Hello XMPP!

I used commandsex-1.85-beta to test this and builded with your Plugin Builder (IN that btw there was an invalid pluginyml generated / missing space be4 nano suite component) / also tried the Bundle version..

**Comment by keir-nellyer** [comment]
Fixed, will be included in the next update! Thanks for reporting!

[Commit](https://github.com/iKeirNez/Minecraft-CommandsEX/commit/5441e324d568438eb44c575a397b7a12a2251257)
