### ISSUE TITLE
/invsee for offline players

### ISSUE THREAD

**Issue by ghost** [CommandsEX/Minecraft-CommandsEX#49]
Hi,
i had some griefers on my server while i was offline and they killed some of my players and took their items with them. I wanted to take their stuff back with /invsee but the command seems not to work for offline players. And griefers won´t come back.

Could you please fix the command /invsee to work for offline users, too?
(Maybe store inventorys on logout in a mysql table.)

**Comment by keir-nellyer** [comment]
Fixed this, will release an official update soon.
