### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by reconteam24** [CommandsEX/Minecraft-CommandsEX#5]
Hi. Sorry to bother you but how do i install CommandsEX

**Comment by keir-nellyer** [comment]
Heres a guide on how to install Bukkit plugins: http://wiki.bukkit.org/Installing_Plugins

Once the server has been started at least once with CommandsEX running it will create a folder in the plugins folder called CommandsEX, in there you will find a config.yml file where you can edit various aspects of the plugin.

You can also go here: http://commandsex.sourceforge.net/
to choose exactly what features you would like in the plugin!
