### ISSUE TITLE
CommandsEX + MobArena

### ISSUE THREAD

**Issue by Xarias09** [CommandsEX/Minecraft-CommandsEX#53]
MobArena: v0.94.4.96
Spigot: 763
CommandsEX v2.0 - 1.5.1

PasteBin: http://pastebin.com/n9BqyaeR

Something doing bad with your slap(unslap??) command??

**Comment by OxideDevelopment** [comment]
Seems like MobArena's fault, as It didn't handle the event properly.

**Comment by kezz** [comment]
:+1: for using Spigot & CommandsEX, however, this issue is with Mob Arena not handling a Teleport event properly.
