### ISSUE TITLE
Some commands aren't functional

### ISSUE THREAD

**Issue by AlternetEightiar** [CommandsEX/Minecraft-CommandsEX#62]
The /spawn command tells me there is an error so does /setspawn
/slap does the same thing. A lot of the features do not work, is there something i needed to select for them to work?
Also are you able to add a messages folder to this so we can customize the command messages

**Comment by keir-nellyer** [comment]
This plugin hasn't been updated in over 2 years, its abandoned as I and the other developer's just don't have the time for it now due to work, college and IRL stuff. Sorry to disappoint you. Something like Essentials would give you similar features though.
