### ISSUE TITLE
Invisible Issues

### ISSUE THREAD

**Issue by ghost** [CommandsEX/Minecraft-CommandsEX#8]
There seems to be an issue with the /inv command. Whenever I go invisible it says I "joined" the game instead of left. When I reappear I says I left the game. Just something I thought maybe has not been mentioned or might be an issue with my setup.

**Comment by keir-nellyer** [comment]
Fixed, will be included in the next version of CommandsEX, thanks for letting us know! You can view the commit at 828fdf8
